spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti6?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username : root
    password : 123456
    driver-class-name: com.mysql.jdbc.Driver


#解决在部署时候，创建数据库表时，缺少历史表，以及无数据问题
  activiti:
    db-history-used: true
    history-level: full

